import Foundation
import COR

/// One recorded battle: the exact inputs of
/// `TacticalSim(players:units:seed:)` plus the full action stream.
/// States are never stored — every intermediate state is regenerated by
/// deterministic replay, which `MultiplayerTests` proves exact.
struct Replay {

	/// Bump when the recipe changes (factory, `.base` rosters, `TacticalAction`
	/// layout): stale files are rejected — regeneration is cheap.
	/// v3: the factory no longer appends seats-1+ rosters (a25d286) —
	/// `makeSim()` composes the full unit list itself.
	/// v4: tactical maps have a compile-time 32×32 size, so the replay header
	/// no longer stores a runtime map size.
	static let version: UInt16 = 4
	static let magic: UInt32 = 0x50475250 // "PGRP"

	struct Seat {
		var country: Country
		var prestige: UInt16
		var baseLevel: UInt8
		var tier: UInt8
	}

	var seed: Int64
	var seats: [Seat]
	var objective: Objective = .none
	var forts: UInt8 = 0
	var actions: [TacticalAction] = []
	var winner: Team = .none
	var days: UInt16 = 0
}

extension Replay {

	/// Rebuilds the battle's initial state, identical to what the generator saw.
	/// The factory places exactly the units it is given (app callers compose
	/// campaign rosters + aux themselves), so every seat's `.base` roster is
	/// composed here; training battles carry no aux.
	func makeSim() -> TacticalSim {
		TacticalSim(
			players: seats.map { s in
				Player(
					country: s.country,
					type: .ai,
					prestige: s.prestige,
					baseLevel: s.baseLevel,
					tier: s.tier
				)
			},
			units: seats.flatMap { s -> [COR.Unit] in .base(s.country, lvl: s.baseLevel) },
			seed: Int(seed),
			objective: objective,
			forts: Int(forts)
		)
	}
}

// MARK: - File IO

extension Replay {

	func data() -> Data {
		var w = ByteWriter()
		w.put(Self.magic)
		w.put(Self.version)
		w.put(UInt16(MemoryLayout<TacticalAction>.size))
		w.put(UInt8(seats.count))
		w.put(winner.rawValue)
		w.put(UInt8(0)) // pad
		w.put(days)
		w.put(seed)
		let objectiveRecord: (kind: UInt8, team: UInt8, day: UInt16) = switch objective {
		case .none: (0, Team.none.rawValue, 0)
		case .survive(let team, let day): (1, team.rawValue, day)
		}
		w.put(objectiveRecord.kind)
		w.put(objectiveRecord.team)
		w.put(objectiveRecord.day)
		w.put(forts)
		for s in seats {
			w.put(s.country.rawValue)
			w.put(s.prestige)
			w.put(s.baseLevel)
			w.put(s.tier)
		}
		w.put(UInt32(actions.count))
		for a in actions { w.put(a) }
		return w.data
	}

	init(data: Data, path: String) throws {
		var r = ByteReader(data: data)
		guard
			r.take(UInt32.self) == Self.magic,
			r.take(UInt16.self) == Self.version,
			r.take(UInt16.self) == UInt16(MemoryLayout<TacticalAction>.size)
		else { throw TrainError.badFile(path) }

		guard
			let seatCount = r.take(UInt8.self),
			let winnerRaw = r.take(UInt8.self), let winner = Team(rawValue: winnerRaw),
			r.take(UInt8.self) != nil, // pad
			let days = r.take(UInt16.self),
			let seed = r.take(Int64.self),
			let objectiveKind = r.take(UInt8.self),
			let objectiveTeamRaw = r.take(UInt8.self),
			let objectiveTeam = Team(rawValue: objectiveTeamRaw),
			let objectiveDay = r.take(UInt16.self),
			let forts = r.take(UInt8.self)
		else { throw TrainError.badFile(path) }
		let objective: Objective
		switch objectiveKind {
		case 0 where objectiveTeam == .none && objectiveDay == 0:
			objective = .none
		case 1 where objectiveTeam != .none:
			objective = .survive(objectiveTeam, day: objectiveDay)
		default:
			throw TrainError.badFile(path)
		}

		var seats: [Seat] = []
		for _ in 0..<seatCount {
			guard
				let countryRaw = r.take(UInt8.self), let country = Country(rawValue: countryRaw),
				let prestige = r.take(UInt16.self),
				let baseLevel = r.take(UInt8.self),
				let tier = r.take(UInt8.self)
			else { throw TrainError.badFile(path) }
			seats.append(Seat(country: country, prestige: prestige, baseLevel: baseLevel, tier: tier))
		}

		guard let actionCount = r.take(UInt32.self) else { throw TrainError.badFile(path) }
		var actions: [TacticalAction] = []
		actions.reserveCapacity(Int(actionCount))
		for _ in 0..<actionCount {
			guard let action = r.take(TacticalAction.self) else { throw TrainError.badFile(path) }
			actions.append(action)
		}
		guard r.isAtEnd else { throw TrainError.badFile(path) }

		self.init(
			seed: seed, seats: seats,
			objective: objective, forts: forts,
			actions: actions, winner: winner, days: days
		)
	}

	func write(to url: URL) throws { try data().write(to: url) }

	static func read(_ url: URL) throws -> Replay {
		try Replay(data: Data(contentsOf: url), path: url.path)
	}
}

// MARK: - Verification

extension Replay {

	/// Rebuilds the battle from the file and replays every action; throws if
	/// the outcome diverges from the recorded one.
	@discardableResult
	static func check(_ url: URL) throws -> Replay {
		let replay = try read(url)
		var sim = replay.makeSim()
		for action in replay.actions { _ = sim.reduce(action) }
		guard
			(sim.winner ?? .none) == replay.winner,
			UInt16(sim.day) == replay.days
		else { throw TrainError.mismatch(url.path) }
		return replay
	}

	static func inspect(_ args: [String]) throws {
		guard !args.isEmpty else { throw TrainError.usage("replay <file> ...") }
		for path in args {
			let replay = try check(URL(fileURLWithPath: path))
			let seats = replay.seats.map { "\($0.country)" }.joined(separator: " vs ")
			print("\(path): \(seats), 32x32, \(replay.actions.count) actions, \(replay.days) days, winner: \(replay.winner) — OK")
		}
	}
}

// MARK: - Raw little-endian records via the core `encode`/`decode` primitives

struct ByteWriter {
	var data = Data()

	mutating func put<T: BitwiseCopyable>(_ value: T) {
		data.append(encode(value))
	}
}

struct ByteReader {
	let data: Data
	var offset = 0
	var isAtEnd: Bool { offset == data.count }

	mutating func take<T: BitwiseCopyable>(_ type: T.Type = T.self) -> T? {
		let n = MemoryLayout<T>.size
		guard offset + n <= data.count else { return nil }
		defer { offset += n }
		return decode(data.subdata(in: offset ..< offset + n))
	}
}

enum TrainError: Error, CustomStringConvertible {
	case usage(String)
	case badFile(String)
	case mismatch(String)
	case failed(String)

	var description: String {
		switch self {
		case .usage(let s): "usage: \(s)"
		case .badFile(let s): "unreadable or stale replay: \(s)"
		case .mismatch(let s): "replay does not reproduce its recorded outcome: \(s)"
		case .failed(let s): s
		}
	}
}
