import Foundation

/// One recorded battle: the exact inputs of
/// `TacticalState(players:units:size:seed:)` plus the full action stream.
/// States are never stored — every intermediate state is regenerated by
/// deterministic replay, which `MultiplayerTests` proves exact.
struct Replay {

	/// Bump when the recipe changes (factory, `.base` rosters, `TacticalAction`
	/// layout): stale files are rejected — regeneration is cheap.
	static let version: UInt16 = 1
	static let magic: UInt32 = 0x50475250 // "PGRP"

	struct Seat {
		var country: Country
		var prestige: UInt16
		var baseLevel: UInt8
		var tier: UInt8
	}

	var size: UInt8
	var seed: Int64
	var seats: [Seat]
	var actions: [TacticalAction] = []
	var winner: Team = .none
	var days: UInt16 = 0
}

extension Replay {

	/// Rebuilds the battle's initial state, identical to what the generator saw.
	/// The factory appends `.base` rosters for seats 1+ itself; seat 0's roster
	/// is passed explicitly with the same recipe.
	func makeState() -> TacticalState {
		TacticalState(
			players: seats.map { s in
				Player(
					country: s.country,
					type: .ai,
					prestige: s.prestige,
					baseLevel: s.baseLevel,
					tier: s.tier
				)
			},
			units: .base(seats[0].country, lvl: seats[0].baseLevel),
			size: Int(size),
			seed: Int(seed)
		)
	}
}

// MARK: - File IO

extension Replay {

	func data() -> Data {
		var w = ByteWriter()
		w.put(Self.magic)
		w.put(Self.version)
		w.put(UInt16(MemoryLayout<TacticalAction>.size))
		w.put(size)
		w.put(UInt8(seats.count))
		w.put(winner.rawValue)
		w.put(UInt8(0)) // pad
		w.put(days)
		w.put(seed)
		for s in seats {
			w.put(s.country.rawValue)
			w.put(s.prestige)
			w.put(s.baseLevel)
			w.put(s.tier)
		}
		w.put(UInt32(actions.count))
		for a in actions { w.put(a) }
		return w.data
	}

	init(data: Data, path: String) throws {
		var r = ByteReader(data: data)
		guard
			r.take(UInt32.self) == Self.magic,
			r.take(UInt16.self) == Self.version,
			r.take(UInt16.self) == UInt16(MemoryLayout<TacticalAction>.size)
		else { throw TrainError.badFile(path) }

		guard
			let size = r.take(UInt8.self),
			let seatCount = r.take(UInt8.self),
			let winnerRaw = r.take(UInt8.self), let winner = Team(rawValue: winnerRaw),
			r.take(UInt8.self) != nil, // pad
			let days = r.take(UInt16.self),
			let seed = r.take(Int64.self)
		else { throw TrainError.badFile(path) }

		var seats: [Seat] = []
		for _ in 0..<seatCount {
			guard
				let countryRaw = r.take(UInt8.self), let country = Country(rawValue: countryRaw),
				let prestige = r.take(UInt16.self),
				let baseLevel = r.take(UInt8.self),
				let tier = r.take(UInt8.self)
			else { throw TrainError.badFile(path) }
			seats.append(Seat(country: country, prestige: prestige, baseLevel: baseLevel, tier: tier))
		}

		guard let actionCount = r.take(UInt32.self) else { throw TrainError.badFile(path) }
		var actions: [TacticalAction] = []
		actions.reserveCapacity(Int(actionCount))
		for _ in 0..<actionCount {
			guard let action = r.take(TacticalAction.self) else { throw TrainError.badFile(path) }
			actions.append(action)
		}

		self.init(
			size: size, seed: seed, seats: seats,
			actions: actions, winner: winner, days: days
		)
	}

	func write(to url: URL) throws { try data().write(to: url) }

	static func read(_ url: URL) throws -> Replay {
		try Replay(data: Data(contentsOf: url), path: url.path)
	}
}

// MARK: - Verification

extension Replay {

	/// Rebuilds the battle from the file and replays every action; throws if
	/// the outcome diverges from the recorded one.
	@discardableResult
	static func check(_ url: URL) throws -> Replay {
		let replay = try read(url)
		var state = replay.makeState()
		for action in replay.actions { _ = state.reduce(action) }
		guard
			(state.sim.winner ?? .none) == replay.winner,
			UInt16(state.sim.day) == replay.days
		else { throw TrainError.mismatch(url.path) }
		return replay
	}

	static func inspect(_ args: [String]) throws {
		guard !args.isEmpty else { throw TrainError.usage("replay <file> ...") }
		TacticalState.logsMapGen = false
		for path in args {
			let replay = try check(URL(fileURLWithPath: path))
			let seats = replay.seats.map { "\($0.country)" }.joined(separator: " vs ")
			print("\(path): \(seats), \(replay.size)x\(replay.size), \(replay.actions.count) actions, \(replay.days) days, winner: \(replay.winner) — OK")
		}
	}
}

// MARK: - Raw little-endian records via the core `encode`/`decode` primitives

struct ByteWriter {
	var data = Data()

	mutating func put<T: BitwiseCopyable>(_ value: T) {
		data.append(encode(value))
	}
}

struct ByteReader {
	let data: Data
	var offset = 0

	mutating func take<T: BitwiseCopyable>(_ type: T.Type = T.self) -> T? {
		let n = MemoryLayout<T>.size
		guard offset + n <= data.count else { return nil }
		defer { offset += n }
		return decode(data.subdata(in: offset ..< offset + n))
	}
}

enum TrainError: Error, CustomStringConvertible {
	case usage(String)
	case badFile(String)
	case mismatch(String)
	case failed(String)

	var description: String {
		switch self {
		case .usage(let s): "usage: \(s)"
		case .badFile(let s): "unreadable or stale replay: \(s)"
		case .mismatch(let s): "replay does not reproduce its recorded outcome: \(s)"
		case .failed(let s): s
		}
	}
}
