import Testing
import Foundation
@testable import COR

struct RNGTests {

	@Test func randomDistribution() {
		var d20 = D20()
		var bins = [20 of UInt16](repeating: 0)

		let throwsCount = 20_000

		(0 ..< throwsCount).forEach { _ in
			bins[d20()] += 1
		}

		// Pearson's chi-squared goodness-of-fit against a uniform distribution.
		let expected = Double(throwsCount) / Double(bins.count)
		let chiSquared = bins.indices.reduce(0.0) { sum, i in
			let delta = Double(bins[i]) - expected
			return sum + delta * delta / expected
		}

		// Critical value for 19 degrees of freedom (20 bins - 1) at a very
		// generous p = 0.001. A genuinely uniform sample exceeds this less than
		// 0.1% of the time, so tail variance alone won't fail the test.
		let criticalValue = 43.82

		let str = bins.indices
			.map { i in "\(bins[i])" }
			.joined(separator: ", ")

		print("Bins: \(str)\nChi-squared: \(chiSquared), must be below \(criticalValue) for 19 dof")
		#expect(chiSquared < criticalValue)
	}

	@Test func duelExpectedMatchesResolve() {
		// The whole point of the Duel seam: `expected()` is the mean of `resolve()`
		// over the *same* curve, table-testable with no map or units. If they ever
		// drift, the AI is planning against a damage model the engine won't roll.
		var report = "Duel expected-vs-empirical:"
		let samples = 4_000

		for hp in stride(from: UInt8(1), through: 15, by: 2) {
			for dif in Int8(-12) ... 20 {
				for crit in [false, true] {
					for evasion in [false, true] {
						let duel = Duel(atk: dif, def: 0, hp: hp, crit: crit, evasion: evasion)

						var rng = D20(seed: 0xA5A5 ^ UInt64(hp) &* 131
							&+ UInt64(bitPattern: Int64(dif)) << 8
							&+ (crit ? 1 : 0) << 16 &+ (evasion ? 1 : 0) << 17)
						var sum: UInt64 = 0
						for _ in 0 ..< samples { sum += UInt64(duel.resolve(&rng)) }

						let empirical = Double(sum) / Double(samples)
						let expected = Double(duel.expected())
						report += "\ndif: \(dif) hp: \(hp) crit: \(crit) ev: \(evasion)"
							+ " expected: \(expected) empirical: \(empirical)"
						#expect(
							abs(empirical - expected) <= 1.0,
							"dif=\(dif) hp=\(hp) crit=\(crit) ev=\(evasion): expected \(expected), empirical \(empirical)"
						)
					}
				}
			}
		}
		print(report)
	}

	@Test func damageCurveTable() throws {
		// The tuning view of the curve: the exact per-round damage distribution
		// for each `dif`, derived from `Duel.thresholds` (faces of the d20 above
		// each threshold — no dice involved). Written to the repository-level
		// `tmp/damage-curve.md` so a threshold tweak in `Duel` shows up as a table diff.
		var md = """
		# Duel damage curve

		Generated by `RNGTests.damageCurveTable` — regenerate by running the test.
		Per-round damage distribution over the d20. `rounds = (hp + 2) / 3`, so a
		full-strength unit (hp 15) rolls 5 rounds. `crit` ×1.15, `evasion` ×0.85.

		| dif | t1…t4 | 0 | 1 | 2 | 3 | 4 | E/round | E hp15 |
		|---:|:---|---:|---:|---:|---:|---:|---:|---:|
		"""

		var previous = 0
		for dif in Int8(-12) ... 20 {
			let duel = Duel(atk: dif, def: 0, hp: 15, crit: false, evasion: false)
			let ts = duel.thresholds

			// faces[k] = die faces (of 20) dealing at least k damage
			var faces: [6 of Int] = [20, 0, 0, 0, 0, 0]
			for k in 1 ... 4 { faces[k] = max(0, 19 - ts[k - 1]) }

			let perRound = faces[1] + faces[2] + faces[3] + faces[4]
			let e15 = (5 * perRound * 500 + 5_000) / 10_000
			#expect(duel.expected() == UInt8(clamping: e15))
			#expect(perRound >= previous, "curve must not dip as dif grows")
			previous = perRound

			let percents = (0 ... 4)
				.map { k in "\((faces[k] - faces[k + 1]) * 5)%" }
				.joined(separator: " | ")
			md += unsafe "\n| \(dif) | \(ts[0]) \(ts[1]) \(ts[2]) \(ts[3]) | \(percents) "
				+ "| \(String(format: "%.2f", Double(perRound) / 20)) | \(e15) |"
		}

		let url = URL(fileURLWithPath: #filePath)
			.deletingLastPathComponent()
			.deletingLastPathComponent()
			.deletingLastPathComponent()
			.appendingPathComponent("tmp/damage-curve.md")
		try FileManager.default.createDirectory(
			at: url.deletingLastPathComponent(),
			withIntermediateDirectories: true
		)
		try md.write(to: url, atomically: true, encoding: .utf8)
		print(md)
	}

	@Test func damageCalculation() {
		var report = "Damage table:"
		var sim = TacticalSim.xs

		var u0 = Unit(model: .regular, country: .den)
		var u1 = Unit(model: .regular, country: .usa)
		u0.reset()
		u1.reset()

		let u0id = sim.spawn(u0, at: XY(1, 1))
		let u1id = sim.spawn(u1, at: XY(2, 2))

		let baseDif = Int(u0.atk(u1)) - Int(u1.def(u0))
		var dmgs: [(Float, UInt8, UInt8)] = []

		for atkMod in Int8(-15)...24 {
			sim.d20 = D20()
			var events: [TacticalEvent] = []
			var min = UInt8.max, max = UInt8.min
			let sum: UInt32 = (0 ..< 512).reduce(0) { acc, _ in
				sim.units[u0id] = u0
				sim.units[u1id] = u1
				sim.fire(src: u0id, dst: u1id, defMod: -atkMod, into: &events)
				let dmg = sim.units[u1id].maxHP - sim.units[u1id].hp
				if dmg > max { max = dmg }
				if dmg < min { min = dmg }
				return acc + UInt32(dmg)
			}

			let avg = Float(sum) / 512
			let dif = baseDif + Int(atkMod)
			if dif >= 0 { #expect(avg > 0) }
			dmgs.append((avg, min, max))
			report += "\ndif: \(dif) dmg: \(avg) \(min)...\(max)"
		}

		#expect(dmgs.first!.0 < dmgs.last!.0)
		print(report)
	}
}

extension TacticalSim {

	static var xs: Self {
		var map = Map<32, Terrain>(size: 4, zero: .field)
		let cities: [(XY, Country)] = [
			(XY(0, 0), .den),
			(XY(3, 3), .usa),
		]
		cities.forEach { x, _ in map[x] = .city }

		let players: [Player] = [
			Player(country: .den, type: .human, prestige: 0xF00),
			Player(country: .usa, type: .human, prestige: 0xF00),
		]

		return TacticalSim(
			map: map,
			players: players,
			cities: cities,
			units: []
		)
	}
}
