name: CI

on:
  [push]

jobs:
  test:
    name: Test COR package
    runs-on: macos-26

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: swift test --package-path COR
